# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SequentialNumbering
                                 A QGIS plugin
 Sequential attribute numbering tool
 Generated by Plugin Builder: http://jonah-sullivan.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-30
        copyright            : (C) 2026 by Adesh K
        email                : kadesh629@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


def classFactory(iface):
    """Load SequentialNumbering class from file SequentialNumbering.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .squential_numbering import SequentialNumbering
    return SequentialNumbering(iface)
