# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SequentialNumberingDockWidget
                                 A QGIS plugin
 Sequential attribute numbering tool
 Generated by Plugin Builder: http://jonah-sullivan.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-30
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Adesh K
        email                : kadesh629@hotmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal
from qgis.core import QgsProject, QgsMapLayer

FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        'squential_numbering_dockwidget_base.ui'))


class SequentialNumberingDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        super(SequentialNumberingDockWidget, self).__init__(parent)

        self.setupUi(self)

        self.layers = []

        self.load_layers()

        self.cmbLayer.currentIndexChanged.connect(
            self.load_fields
        )
    
    def load_layers(self):

        self.cmbLayer.clear()

        self.layers.clear()

        for layer in QgsProject.instance().mapLayers().values():

            if layer.type() == QgsMapLayer.VectorLayer:

                self.layers.append(layer)

                self.cmbLayer.addItem(layer.name())

        self.load_fields()

    def load_fields(self):

        self.cmbField.clear()

        if not self.layers:
            return

        layer = self.layers[
            self.cmbLayer.currentIndex()
        ]

        for field in layer.fields():

            self.cmbField.addItem(
                field.name()
            )

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
