# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PdfToTiffConverter
                                 A QGIS plugin
 This plugin converts pdf's to tif's
 Generated by Plugin Builder: http://jonah-sullivan.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-06-12
        copyright            : (C) 2026 by Adesh K
        email                : kadesh629@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


def classFactory(iface):
    """Load PdfToTiffConverter class from file PdfToTiffConverter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pdf_to_tiff import PdfToTiffConverter
    return PdfToTiffConverter(iface)
