# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PdfToTiffConverterDialog
                                 A QGIS plugin
 This plugin converts pdf's to tif's
 Generated by Plugin Builder: http://jonah-sullivan.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-06-12
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Adesh K
        email                : kadesh629@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtWidgets import QFileDialog

FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        'pdf_to_tiff_dialog_base.ui'))


class PdfToTiffConverterDialog(QtWidgets.QDialog, FORM_CLASS):

    def __init__(self, parent=None):
        super(PdfToTiffConverterDialog, self).__init__(parent)

        self.setupUi(self)

        # Connect buttons
        self.btnPdf.clicked.connect(self.select_pdf)
        self.btnTif.clicked.connect(self.select_tif)

        # Add DPI values
        self.cmbDpi.addItems(["150", "300", "600"])

    def select_pdf(self):
        file_name, _ = QFileDialog.getOpenFileName(
            self,
            "Select PDF",
            "",
            "PDF Files (*.pdf)"
        )

        if file_name:
            self.txtPdf.setText(file_name)

    def select_tif(self):
        file_name, _ = QFileDialog.getSaveFileName(
            self,
            "Save TIFF",
            "",
            "TIFF Files (*.tif)"
        )

        if file_name:
            self.txtTif.setText(file_name)